apiVersion: v1
entries:
  srevox-db-auditor:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2026-09-14T15:00:00.000Z"
    description: Srevox DB Auditor - Enterprise Database Audit & Change Intelligence Platform
    digest: ""
    name: srevox-db-auditor
    type: application
    urls:
    - srevox-db-auditor-0.0.1.tgz
    version: 0.0.1
generated: "2026-09-14T15:00:00.000Z"
